model_name=MoSTE

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./data/data_series/ \
  --data_path BTH.csv \
  --prior_graph_path ./data/data_adj/adj_BTH_new.pkl \
  --model_id BTH_96_24 \
  --model $model_name \
  --data only_do \
  --features M \
  --target yuqiaoshuikuchukou \
  --freq h \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 24 \
  --enc_in 24 \
  --c_out 24 \
  --d_model 64 \
  --e_layers 2 \
  --d_ff 128 \
  --down_sampling_layers 3 \
  --down_sampling_method avg \
  --down_sampling_window 2 \
  --steps_per_day 6 \
  --structure_weight 0.1 \
  --batch_size 32 \
  --train_epochs 10 \
  --patience 3 \
  --learning_rate 0.0001 \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./data/data_series/ \
  --data_path BTH.csv \
  --prior_graph_path ./data/data_adj/adj_BTH_new.pkl \
  --model_id BTH_96_48 \
  --model $model_name \
  --data only_do \
  --features M \
  --target yuqiaoshuikuchukou \
  --freq h \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 48 \
  --enc_in 24 \
  --c_out 24 \
  --d_model 64 \
  --e_layers 2 \
  --d_ff 128 \
  --down_sampling_layers 3 \
  --down_sampling_method avg \
  --down_sampling_window 2 \
  --steps_per_day 6 \
  --structure_weight 0.1 \
  --batch_size 32 \
  --train_epochs 10 \
  --patience 3 \
  --learning_rate 0.0001 \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./data/data_series/ \
  --data_path BTH.csv \
  --prior_graph_path ./data/data_adj/adj_BTH_new.pkl \
  --model_id BTH_96_72 \
  --model $model_name \
  --data only_do \
  --features M \
  --target yuqiaoshuikuchukou \
  --freq h \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 72 \
  --enc_in 24 \
  --c_out 24 \
  --d_model 64 \
  --e_layers 2 \
  --d_ff 128 \
  --down_sampling_layers 3 \
  --down_sampling_method avg \
  --down_sampling_window 2 \
  --steps_per_day 6 \
  --structure_weight 0.1 \
  --batch_size 32 \
  --train_epochs 10 \
  --patience 3 \
  --learning_rate 0.0001 \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./data/data_series/ \
  --data_path BTH.csv \
  --prior_graph_path ./data/data_adj/adj_BTH_new.pkl \
  --model_id BTH_96_96 \
  --model $model_name \
  --data only_do \
  --features M \
  --target yuqiaoshuikuchukou \
  --freq h \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --enc_in 24 \
  --c_out 24 \
  --d_model 64 \
  --e_layers 2 \
  --d_ff 128 \
  --down_sampling_layers 3 \
  --down_sampling_method avg \
  --down_sampling_window 2 \
  --steps_per_day 6 \
  --structure_weight 0.1 \
  --batch_size 32 \
  --train_epochs 10 \
  --patience 3 \
  --learning_rate 0.0001 \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./data/data_series/ \
  --data_path BTH.csv \
  --prior_graph_path ./data/data_adj/adj_BTH_new.pkl \
  --model_id BTH_96_120 \
  --model $model_name \
  --data only_do \
  --features M \
  --target yuqiaoshuikuchukou \
  --freq h \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 120 \
  --enc_in 24 \
  --c_out 24 \
  --d_model 64 \
  --e_layers 2 \
  --d_ff 128 \
  --down_sampling_layers 3 \
  --down_sampling_method avg \
  --down_sampling_window 2 \
  --steps_per_day 6 \
  --structure_weight 0.1 \
  --batch_size 32 \
  --train_epochs 10 \
  --patience 3 \
  --learning_rate 0.0001 \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./data/data_series/ \
  --data_path BTH.csv \
  --prior_graph_path ./data/data_adj/adj_BTH_new.pkl \
  --model_id BTH_96_192 \
  --model $model_name \
  --data only_do \
  --features M \
  --target yuqiaoshuikuchukou \
  --freq h \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --enc_in 24 \
  --c_out 24 \
  --d_model 64 \
  --e_layers 2 \
  --d_ff 128 \
  --down_sampling_layers 3 \
  --down_sampling_method avg \
  --down_sampling_window 2 \
  --steps_per_day 6 \
  --structure_weight 0.1 \
  --batch_size 32 \
  --train_epochs 10 \
  --patience 3 \
  --learning_rate 0.0001 \
  --des 'Exp' \
  --itr 1
